# Generated by Django 3.0.7 on 2020-08-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_skus_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skus',
            name='code',
        ),
    ]
