# Generated by Django 3.0.7 on 2020-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200824_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skus',
            name='specification',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
