# Generated by Django 3.0.7 on 2020-08-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200824_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='idcategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='idgroups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Groups'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='idskus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Skus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='idsubcategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Subcategories'),
            preserve_default=False,
        ),
    ]
